export const CHANGE_ADDRESS_TEXT = "CHANGE_ADDRESS_TEXT";
export const SET_ACTIVE_CHANNEL = "SET_ACTIVE_CHANNEL";
export const HANDLE_PRIVKEY_CHANGE = "HANDLE_PRIVKEY_CHANGE";
export const HANDLE_SHOWNEWCHANNELFORM_TOGGLE = "HANDLE_SHOWNEWCHANNELFORM_TOGGLE";