export const GET_PENDING_CHANNELS = "GET_PENDING_CHANNELS";
export const GET_REQUESTED_CHANNELS = "GET_REQUESTED_CHANNELS";
export const GET_CHANNEL_DETAILS = "GET_CHANNEL_DETAILS";
export const GET_HIGHEST_NONCE = "GET_HIGHEST_NONCE";
export const GET_LATEST_TX = "GET_LATEST_TX";
export const GET_HIGHEST_SIGNED_NONCE = "GET_HIGHEST_SIGNED_NONCE";
export const GET_LATEST_SIGNED_TX = "GET_LATEST_SIGNED_TX";